name: Lighthouse Checker and Deploy
on:
  pull_request:
    types: [closed]

jobs:
  # First Lighthouse check (before Deploy)
  lighthouse_check_first:
    runs-on: ubuntu-latest
    name: Lighthouse Check First
    steps:
      - uses: actions/checkout@master
      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.7
        with:
          path: .env
          log-variables: true
          mask-variables: false
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### First Lighthouse check (before Deploy) 👇
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          outputDirectory: "/tmp/artifacts"
          emulatedFormFactor: all
          locale: us
          # Put here all URLs that you want to test.
          # URLs should be separated by coma ",".
          # Do not add a coma to the last URL.
          urls: ${{ steps.dotenv.outputs.lighthouse_urls }}

  # Deploy
  deploy:
    needs: lighthouse_check_first
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment started."
      - run: echo "Deployment successfully completed!"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Deployment successfully completed! 🎉

  # Second Lighthouse check (before Deploy)
  lighthouse_check_second:
    runs-on: ubuntu-latest
    name: Lighthouse Check Second
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Second Lighthouse check (after Deploy) 👇
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          outputDirectory: "/tmp/artifacts"
          emulatedFormFactor: all
          locale: us
          prCommentSaveOld: true
          # Put here all URLs that you want to test.
          # URLs should be separated by coma ",".
          # Do not add a coma to the last URL.
          urls: >-
            ${{ secrets.SITE_URL }}
